matrix:
  include:
    - language: node_js
      node_js:
        - "9"
      script:
        - npm install
        - npm run lint
        - npm test

    - os: osx
      language: objective-c
      osx_image: xcode10.2
      env:
        - OS: 'ios'

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      # https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959
      before_script:
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      android:
        components:
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-21
          - android-27
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - OS: 'android'

script:
  # See https://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  # Clear out whatever version of NVM Travis has.
  # Their version of NVM is probably old.
  - rm -rf ~/.nvm

  # Grab NVM.
  - git clone https://github.com/creationix/nvm.git ~/.nvm

  # Checkout the latest stable tag.
  # Note that you can just hardcode a preferred version here.
  - (cd ~/.nvm; git checkout `git describe --abbrev=0 --tags`)

  # Add nvm command available to shell
  - source ~/.nvm/nvm.sh

  # Install latest version of Node
  - nvm install 11.6.0

  # Run build script
  - npm run ci

